---
# The command to run the thelounge command: `ansible-playbook -i inventory/hosts setup.yml --tags=command-thelounge -e command=COMMAND_HERE`

- name: Fail if playbook called incorrectly
  ansible.builtin.fail:
    msg: "The `command` variable needs to be provided via --extra-vars"
  when: "command is not defined"

# See: https://github.com/thelounge/thelounge-docker/blob/master/README.md#executing-commands-in-the-container
- name: Run The Lounge command
  ansible.builtin.command:
    cmd: |-
      {{ sysd_docker_host_command }} exec
      {{ thelounge_identifier }}
      node /app/index.js
      {{ command }}
  register: result
  changed_when: result.rc == 0
  failed_when: false
  no_log: true

- name: Display The Lounge command result
  ansible.builtin.debug:
    msg: "The Lounge command result: {{ result.stdout if result.stdout else result.stderr }}"
