# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform The Lounge installation tasks
  when: thelounge_enabled | bool
  tags:
    - setup-all
    - setup-thelounge
    - install-all
    - install-thelounge
  block:
    - name: Validate The Lounge configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install The Lounge
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform The Lounge command execution tasks
  when: thelounge_enabled | bool
  tags:
    - command-thelounge
  block:
    - name: Run The Lounge command
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/command.yml"

- name: Perform The Lounge user creation tasks
  when: thelounge_enabled | bool
  tags:
    - add-thelounge
  block:
    - name: Run The Lounge 'add' command
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/add.yml"

- name: Perform The Lounge uninstallation tasks
  when: not thelounge_enabled | bool
  tags:
    - setup-all
    - setup-thelounge
  block:
    - name: Uninstall The Lounge
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
