# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "thelounge_environment_variable_port", "new": "thelounge_container_http_port" }
    - { "old": "thelounge_redis_host", "new": "thelounge_redis_hostname" }
    - { "old": "thelounge_http_header_content_permission_policy", "new": "thelounge_http_header_permissions_policy" }

- name: Fail if required The Lounge settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - thelounge_uid
    - thelounge_gid
    - thelounge_hostname
    - thelounge_path_prefix
    - thelounge_container_network
    - thelounge_database_hostname
    - thelounge_database_password
    - thelounge_environment_variable_redis_url

- name: Fail if The Lounge storage drver option is invalid
  ansible.builtin.fail:
    msg: >-
      thelounge_environment_variable_storage_driver must be 'local' or 's3'
  when: "thelounge_environment_variable_storage_driver not in ['local', 's3']"

- name: Fail if The Lounge mail driver option is invalid
  ansible.builtin.fail:
    msg: >-
      thelounge_environment_variable_mail_driver must be 'smtp' or 'postmark'
  when: "thelounge_environment_variable_mail_driver not in ['smtp', 'postmark']"

- name: Fail if mailer setting is missing
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) to correctly set up email.
  when: "thelounge_mailer_enabled and lookup('vars', item, default='') | string | length == 0"
  with_items:
    - thelounge_environment_variable_mail_from_address

- name: Fail if SMTP setting is missing (and SMTP is enabled by setting host)
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) to correctly set up email via SMTP.
  when: "thelounge_mailer_enabled | bool and thelounge_environment_variable_mail_driver == 'smtp' and lookup('vars', item, default='') | string | length == 0"
  with_items:
    - thelounge_environment_variable_smtp_host

- name: Run if Traefik is enabled
  when: thelounge_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for The Lounge are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - thelounge_container_labels_traefik_hostname
        - thelounge_container_labels_traefik_path_prefix

    - name: Fail if thelounge_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          thelounge_container_labels_traefik_path_prefix (`{{ thelounge_container_labels_traefik_path_prefix }}`) must be `/`.
          The Lounge does not support hosting under a subpath yet.
      when: "thelounge_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `thelounge_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if thelounge_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          thelounge_container_labels_traefik_path_prefix (`{{ thelounge_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/thelounge`).
      when: "thelounge_container_labels_traefik_path_prefix != '/' and thelounge_container_labels_traefik_path_prefix[-1] == '/'"
